#!/usr/bin/env python
"""Validate audit/backend/requirements.lock, the production resolution.

Model (complements check_mneme_version_parity.py, which guards the floor):

- audit/backend/requirements.txt is the dynamic compatibility floor.
- audit/backend/requirements.lock is the exact, reviewed production
  resolution, generated by scripts/lock_audit_requirements.py and consumed
  only as pip constraints by the production image build.

The lock may deliberately lag the newest published Mneme engine: an Audit
engine upgrade is an explicit reviewed change to the lock. This check
therefore never compares the lock with PyPI or with scripts/core_version.json.

Static checks (no network, no install needed):
1. every lock entry is an exact ``name==version`` pin;
2. the lock was resolved from the current requirements.txt (header hash);
3. every requirement in requirements.txt is locked and its locked version
   satisfies the declared floor.

With --installed, additionally prove the active environment IS the lock:
every locked distribution is installed at exactly the locked version and
nothing outside the lock is installed.
"""
from __future__ import annotations

import argparse
import importlib.metadata
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lock_audit_requirements import LOCK, REQUIREMENTS, requirements_sha256  # noqa: E402

# Installer tooling that pip freeze omits and the lock does not govern.
UNLOCKED_TOOLING = {"pip", "setuptools", "wheel"}


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def version_key(value: str) -> tuple[int, ...]:
    return tuple(int(piece) for piece in re.findall(r"\d+", value)) or (0,)


def read_lock(path: Path) -> tuple[dict[str, str], dict[str, str], list[str]]:
    header: dict[str, str] = {}
    pins: dict[str, str] = {}
    errors: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            match = re.fullmatch(r"#\s*([a-z0-9-]+):\s*(.+)", line)
            if match:
                header[match.group(1)] = match.group(2).strip()
            continue
        match = re.fullmatch(r"([A-Za-z0-9][A-Za-z0-9._-]*)==([A-Za-z0-9.!+_-]+)", line)
        if not match:
            errors.append(f"lock entry is not an exact name==version pin: {line!r}")
            continue
        name = canonical(match.group(1))
        if name in pins:
            errors.append(f"lock pins {name} more than once")
        pins[name] = match.group(2)
    return header, pins, errors


def read_floors(path: Path) -> tuple[dict[str, str], list[str]]:
    floors: dict[str, str] = {}
    errors: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        match = re.fullmatch(r"([A-Za-z0-9][A-Za-z0-9._-]*)(\[[^\]]+\])?>=(\d+(?:\.\d+)*)", line)
        if not match:
            errors.append(f"requirements.txt entry is not a 'name>=X.Y.Z' floor: {line!r}")
            continue
        floors[canonical(match.group(1))] = match.group(3)
    return floors, errors


def check_static(requirements: Path, lock: Path) -> tuple[list[str], dict[str, str]]:
    header, pins, errors = read_lock(lock)
    floors, floor_errors = read_floors(requirements)
    errors += floor_errors

    expected_hash = requirements_sha256(requirements)
    if header.get("requirements-sha256") != expected_hash:
        errors.append(
            "lock was not resolved from the current requirements.txt "
            f"(header {header.get('requirements-sha256')!r}, current {expected_hash!r}); "
            "regenerate it with scripts/lock_audit_requirements.py"
        )
    for name, floor in floors.items():
        locked = pins.get(name)
        if locked is None:
            errors.append(f"{name} is required but not locked")
        elif version_key(locked) < version_key(floor):
            errors.append(f"locked {name}=={locked} is below the declared floor >={floor}")
    engine = pins.get("mneme-hq", "")
    if engine and header.get("mneme-hq") != engine:
        errors.append(
            f"lock header reports mneme-hq {header.get('mneme-hq')!r} but pins {engine!r}"
        )
    return errors, pins


def check_installed(pins: dict[str, str]) -> list[str]:
    errors: list[str] = []
    installed = {
        canonical(dist.metadata["Name"]): dist.version
        for dist in importlib.metadata.distributions()
        if dist.metadata["Name"]
    }
    for name, locked in sorted(pins.items()):
        actual = installed.get(name)
        if actual is None:
            errors.append(f"{name}=={locked} is locked but not installed")
        elif actual != locked:
            errors.append(f"{name} is installed at {actual}, lock says {locked}")
    for name in sorted(set(installed) - set(pins) - UNLOCKED_TOOLING):
        errors.append(f"{name}=={installed[name]} is installed but not in the lock")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements", type=Path, default=REQUIREMENTS)
    parser.add_argument("--lock", type=Path, default=LOCK)
    parser.add_argument(
        "--installed", action="store_true",
        help="also require the active environment to match the lock exactly",
    )
    args = parser.parse_args(argv)

    if not args.lock.exists():
        print(f"FAIL: production resolution not found: {args.lock}")
        return 1
    errors, pins = check_static(args.requirements, args.lock)
    if args.installed and not errors:
        errors += check_installed(pins)
    if errors:
        print(f"audit-lock: FAIL ({len(errors)} problem(s))")
        for error in errors:
            print(f"  - {error}")
        return 1
    mode = "static + installed environment" if args.installed else "static"
    print(f"audit-lock: OK ({len(pins)} exact pins, {mode})")
    print(f"LOCKED_MNEME_HQ_VERSION={pins.get('mneme-hq', '')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
